# Title displayed in the index page
title = "Johannes K Becker"

# Use this theme
theme = "kodama-theme"

# The URL the site will be built for
base_url = "https://jkbecker.net"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

# Image of your avatar displayed on the landing page
avatar = "static/img/jkbckr.png"
# Image of the favicon
favicon = "static/img/jkbckr.png"

# Your email address showed in the contact section
email = "mail [at] jkbecker.net"

# If you don't want to show your contact information in the index
contact_in_index = true

# Additional menu items
# `Name` is what it is displayed, `path` is the url
menu_items = [
  { path = "#contacts", name = "Contact" },
]