name: Zola on GitHub Pages

on:
  push:
    branches:
      - main 
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@v3.0.0
      - name: Tailwind
        run: |
          cd themes/kodama-theme
          npm install -D tailwindcss
          npx tailwindcss init
          npx tailwindcss -i styles/styles.css -o static/styles/styles.css
      - name: Build only 
        uses: shalzz/zola-deploy-action@v0.17.1
        env:
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts
          # A GitHub token is not necessary when BUILD_ONLY is true
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@v3.0.0
      - name: Tailwind
        run: |
          cd themes/kodama-theme
          npm install -D tailwindcss
          npx tailwindcss init
          npx tailwindcss -i styles/styles.css -o static/styles/styles.css
      - name: Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.17.1
      - name: Build
        run: zola build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
          cname: jkbecker.net
          commit_message: ${{ github.event.head_commit.message }}